<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>

    <TargetFramework>net8.0</TargetFramework>

    <Platforms>AnyCPU;x64;x86</Platforms>

    <Configurations>Debug;Release;Mono;Canary</Configurations>

    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

    <AssemblyTitle>BrawlCrateLib v0.42</AssemblyTitle>

    <Product>BrawlCrateLib</Product>

    <Version>42.0.1</Version>

    <Authors>
      soopercool101;
      Simon381;
      Onium;
      Bryan Moulton;
      BlackJax96;
      libertyernie;
      Sammi Husky
    </Authors>

  </PropertyGroup>


  <!-- REMOVE WPF -->

  <ItemGroup>

    <!-- REMOVE THESE -->
    <!--
    <Reference Include="PresentationCore" />
    <Reference Include="WindowsBase" />
    <Reference Include="System.Xaml" />
    -->

    <Reference Include="OpenTK">
      <HintPath>.\OpenTK.dll</HintPath>
    </Reference>

  </ItemGroup>


  <!-- NuGet replacements -->

  <ItemGroup>

    <PackageReference Include="System.IO.Hashing" Version="8.0.0" />

    <PackageReference Include="System.Drawing.Common" Version="8.0.0" />

  </ItemGroup>


  <!-- Resources -->

  <ItemGroup>

    <EmbeddedResource Include="CustomLists\FighterList.txt" />

    <EmbeddedResource Include="CustomLists\StageList.txt" />

    <EmbeddedResource Include="HardcodedFiles\Textures\metal00.tex0" />

    <EmbeddedResource Include="HardcodedFiles\Textures\TShadow1.tex0" />

    <EmbeddedResource Include="HardcodedFiles\Textures\spycloak00.tex0" />

    <EmbeddedResource Include="HardcodedFiles\Textures\FB.tex0" />

    <EmbeddedResource Include="HardcodedFiles\Models\Static.mdl0" />

  </ItemGroup>


</Project>
